target 'HZThreeParty' do
platform :ios, ‘8.0’
pod 'AFNetworking', '~> 3.0'
pod 'MJRefresh', '~> 3.1'
pod 'SDWebImage', '~> 3.6'
pod 'FMDB', '~> 2.6'
pod 'MBProgressHUD', '~> 1.0'
pod 'SVProgressHUD', '~> 2.0'
pod 'SDCycleScrollView','~> 1.64'
pod 'Mantle', '~> 2.0'
pod 'YTKNetwork', '~> 2.0.1'
pod 'Masonry', '~> 1.0'
pod 'JSONKit', '~> 1.4'
pod 'MJPhotoBrowser'
pod 'MJExtension'
pod 'YYKit'
pod 'KMCGeigerCounter'
pod 'ReactiveObjC', '~> 3.0.0'
end
