platform :ios, '10.0'
target 'HZWeChat' do
pod 'MJRefresh','3.1.15'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~>3.8'
pod 'FMDB', '~>2.7.2'
pod 'SVProgressHUD', '~>2.0'
pod 'Masonry', '~> 1.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'CocoaLumberjack', '~> 3.3.0'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'YYText', '~> 1.0.7'
end
