target 'HZWeiBo' do
platform :ios, ‘7.0’
pod 'AFNetworking', '~> 3.0'
pod 'MJRefresh', '~> 3.1'
pod 'SDWebImage', '~> 3.6'
pod 'FMDB', '~> 2.6'
pod 'MBProgressHUD', '~> 1.0'
pod 'SVProgressHUD', '~> 2.0'
pod 'MJExtension'
pod 'MJPhotoBrowser'
pod 'KMCGeigerCounter'
end

